- id: "NuGet:Azure.ResourceManager:KubernetesConfiguration:"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/kubernetesconfiguration/Azure.ResourceManager.KubernetesConfiguration"
