ort:
  allowedProcessEnvironmentVariableNames:
    - PASSPORT
    - USER_HOME
    - GITHUB_TOKEN
  deniedProcessEnvironmentVariablesSubstrings:
    - PASS
    - SECRET
    - TOKEN
    - USER


  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  licenseFilePatterns:
    licenseFilenames: ["license*"]
    patentFilenames: ["patents"]
    otherLicenseFilenames: ["readme*"]

  packageConfigurationProviders:
    - type: DefaultDir

  packageCurationProviders:
    - type: DefaultFile
    - type: DefaultDir

  severeIssueThreshold: WARNING
  severeRuleViolationThreshold: WARNING

analyzer:
  skip_excluded: true
  allow_dynamic_versions: false
excludes:
  paths:
  - pattern: ".optima/**"
    reason: "DATA_FILE_OF"
    comment: "Optima definition files"
