ort:
  force-overwrite: true
  allowedProcessEnvironmentVariableNames:
    - PASSPORT
    - USER_HOME
    - GITHUB_TOKEN
  deniedProcessEnvironmentVariablesSubstrings:
    - PASS
    - SECRET
    - TOKEN
    - USER


  enableRepositoryPackageConfigurations: true
  enableRepositoryPackageCurations: true

  licenseFilePatterns:
    licenseFilenames: ["license*"]
    patentFilenames: ["patents"]
    rootLicenseFilenames: ["readme*"]

  packageConfigurationProviders:
    - type: DefaultDir
    - type: OrtConfig

  packageCurationProviders:
    - type: DefaultFile
    - type: DefaultDir
    - type: OrtConfig
      enabled: "${USE_ORT_CONFIG_CURATIONS:-true}"

  severeIssueThreshold: WARNING
  severeRuleViolationThreshold: WARNING

analyzer:
  skip_excluded: true
  allow_dynamic_versions: false
excludes:
  paths:
  - pattern: ".optima/**"
    reason: "DATA_FILE_OF"
    comment: "Optima definition files"
