- id: "NuGet:AWSSDK:CodeGuruSecurity:[3.7.568,)"
  curations:
    comment: "Set the VCS path of the module inside the multi-module repository."
    vcs:
      path: "sdk/src/Services/CodeGuruSecurity"
