- id: "Maven:org.apache.logging.log4j:log4j-spring-cloud-config:"
  curations:
    comment: |
      Package resides in its own directory within project's code repository.
    vcs:
      path: "log4j-spring-cloud-config"
