- id: "Maven:org.springframework.boot:spring-boot-configuration-processor:]1.9999,)"
  curations:
    comment: |
      Package resides in its own directory within project's code repository.
    vcs:
      path: "spring-boot-project/spring-boot-tools/spring-boot-configuration-processor"
