- id: "Maven:org.apache.hadoop:hadoop-yarn-server-applicationhistoryservice:"
  curations:
    comment: |
      No SCM info in pom.xml and no source artifacts
      published.
    vcs:
      url: "https://git-wip-us.apache.org/repos/asf/hadoop.git"
      path: "hadoop-yarn-project/hadoop-yarn/hadoop-yarn-server/hadoop-yarn-server-applicationhistoryservice/src/main"
