- id: "Maven:org.apache.maven:maven-settings-builder:"
  curations:
    comment: |
      Package resides in its own directory within project's code repository.
    vcs:
      path: "maven-settings-builder"
