name: Generate and release curations

on:
  workflow_dispatch:
  push:
    tags:
      - "cariad_v[0-9]+.[0-9]+.[0-9]+"

jobs:
  curations:
    name: curations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ort-config
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Generate curations
        run: |
          cd tools/curations/
          ./gradlew tasks --group "generate curations"
          ./gradlew -P githubUsername=oauth2 -P githubToken=${{ secrets.GITHUB_TOKEN }} generateAspNetCoreCuration
          ./gradlew tasks --group "verification"

      - name: Create curations.tar.gz
        run: tar -czf curations.tar.gz -C curations/ .

      - name: Create GitHub Release
        if: ${{ github.event_name == 'push' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes --latest ./curations.tar.gz

      - name: Upload to artifactory
        run: |
          echo "${{ secrets.PLATOSS_CERT_BASE64  }}" | base64 -d > platoss-bundle.pem
          echo "${{ secrets.PLATOSS_KEY_BASE64  }}" | base64 -d >> platoss-bundle.pem
          curl --cert platoss-bundle.pem -u "${{ secrets.PLATOSS_JFROG_USER }}:${{ secrets.PLATOSS_JFROG_TOKEN }}" -T ./curations.tar.gz \
            "https://jfrog.hub.vwgroup.com/artifactory/optima-generic-internal/test/curations.tar.gz"
