name: Generate and release curations

on:
  release:
    types:
      - created

jobs:
  curations:
    name: curations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ort-config
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: microsoft
          java-version: 17
      - name: Generate curations
        run: |
          cd tools/curations/
          ./gradlew tasks --group "generate curations"
          ./gradlew -P githubUsername=oauth2 -P githubToken=${{ secrets.GITHUB_TOKEN }} generateAspNetCoreCuration
          ./gradlew tasks --group "verification"
      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: curations
          path: curations
      - name: Create curations.tar.gz
        run: tar -czf curations.tar.gz -C curations/ .
      - name: Upload curations.tar.gz
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./curations.tar.gz
          asset_name: curations.tar.gz
          asset_content_type: application/gzip
