name: Verification

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
    - name: Setup Java
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      with:
        distribution: temurin
        java-version: 17
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4
      with:
        gradle-home-cache-cleanup: true
    - name: Verify package configurations
      run: ./gradlew -p tools/curations verifyPackageConfigurations
    - name: Verify package curations
      run: ./gradlew -p tools/curations verifyPackageCurations
