name: Verification

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  category-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -U rich pyyaml pydantic-settings
      - name: Run Licensse Classification Category Validation
        run: python cariad/scripts/validation.py

  verification:
    runs-on: ubuntu-latest
    needs: category-validation
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4
        with:
          gradle-home-cache-cleanup:
      - name: Verify package configurations
        run: ./gradlew -p tools/curations verifyPackageConfigurations
      - name: Verify package curations
        run: ./gradlew -p tools/curations verifyPackageCurations
