name: Verification

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Setup Java
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4
      with:
        gradle-home-cache-cleanup: true
    - name: Verify package configurations
      run: ./gradlew -p tools/curations verifyPackageConfigurations
    - name: Verify package curations
      run: ./gradlew -p tools/curations verifyPackageCurations
