name: Verification

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
          cache: gradle
      - name: Verify package curations
        uses: burrunan/gradle-cache-action@v1
        with:
          build-root-directory: tools/curation-generator
          arguments: verifyPackageCurations
