name: Verification

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  category-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -U rich pyyaml pydantic-settings
      - name: Run Licensse Classification Category Validation
        run: python cariad/scripts/validation.py

  verification:
    runs-on: ubuntu-latest
    needs: category-validation
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Setup Java
      uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b # v4
      with:
        gradle-home-cache-cleanup: true
          #- name: Verify package configurations
          #      run: ./gradlew -p tools/curations verifyPackageConfigurations
    - name: Verify package curations
      run: ./gradlew -p tools/curations verifyPackageCurations
