name: Verification

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  verification:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    steps:
    - name: Checkout Repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
    - name: Setup Java
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
      with:
        distribution: temurin
        java-version: 21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4
      with:
        gradle-home-cache-cleanup: true
    - name: Verify package configurations
      run: ./gradlew -p tools/curations verifyPackageConfigurations
    - name: Verify package curations
      run: ./gradlew -p tools/curations verifyPackageCurations
