name: Yaml Linter

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Yaml Lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
